sudo: false
language: ruby
rvm:
- 2.2.5
- 2.3.1
env:
  global:
    secure: MrlvzXT+3Kl9dJ9tZTFhp3CZpaa2H5fJcA/YBtgl5Gl5LDqHQqMRDCxgOoyZQnVA4lQSvlT/Eo7Z1eMswGel34vMB+akWNlk3oRKb1oHDURNGcGs6LRzutPFJB7DLDA8UGZDj0INKkqA7r/pUciMG9Y8xej6oJRJyWURqEw8OmuI+ENXsK0B1CNyOnakuKRaRgMEkip8xKNdoXHfK0qUq+x69eE7HVy38uQ2dRXskOIpu9eE6zZPAw0YGLmsNC63MmEshx/w24prm610NZXpCX0qRZXIlRGPdnE9LjzjNZ5Xw05qM5Chr+5eW97SwHlqtyMTzW/v991y5bVQXK8cbQzvv5t8rOXN5CzIykPtYPQrcOBIBx2c4xEEhIW6xm6faprFpKV6/J31s1lBRPvmUYRbUgv4RJRpaNOioz9rrMdAMoOsG1VtyTKNMIRmfLjf94x7o0JY7mnyjvdHkMVHvTj23Nr9jUVl7lJJjbyjqZsDta6P7N24U46i55FoshfSbADlWbzP3Uj9i1DreVEO+SCSfoA38GdMdm1IJmpwkS8J2bGxNsNgUVczq87YM1LEw3XcdkePAuun4E/pwmoOVguzQ5tNPUbzd4Q5Ig2cjEAJ0wFIJyAKMiOyYGQCbXSYPtruTtda42bpxOWYuITgIHWfKtFaY62J33dtOJW7WeQ=
  matrix:
  - RAKE_TASK=spec
  - RAKE_TASK="travis[integration]" AWS_TRAVIS_DRIVER=aws::us-east-2
  - RAKE_TASK="travis[super_slow]" AWS_TRAVIS_DRIVER=aws::us-east-1
  - RAKE_TASK="machine_image" AWS_TRAVIS_DRIVER=aws::us-east-1
before_script:
- mkdir -p /home/travis/.chef
- ". ./tools/travis_env.sh"
script:
- bundle exec rake build
- bundle exec rake $RAKE_TASK
